package com.harinitech.springboot_security_jwt_rbac_app1.model;

public enum AuditAction {

	// ======================== 🔐 AUTH ========================
	LOGIN, LOGOUT, REFRESH_TOKEN, VALIDATE_TOKEN,

	// ======================== 👤 USER ========================
	USER_REGISTER, USER_UPDATE, USER_DELETE, USER_STATUS_CHANGE, USER_ACCESS_TOGGLE,

	// ======================== 🔑 PASSWORD ========================
	PASSWORD_CHANGE, PASSWORD_RESET_REQUEST, PASSWORD_RESET_COMPLETE,

	// ======================== 🔐 ROLE ========================
	ROLE_ASSIGN, ROLE_REMOVE,

	// ======================== 🔒 SECURITY ========================
	FORCE_LOGOUT, TOKEN_REVOKE, ACCOUNT_LOCK, ACCOUNT_UNLOCK,

	// ======================== 📩 OTP ========================
	OTP_SENT, OTP_VERIFIED, OTP_FAILED,

	// ======================== ⚙️ SYSTEM ========================
	SYSTEM_ERROR, ACCESS_DENIED, ACCOUNT_LOCKED, TOKEN_REFRESH, TOKEN_REUSE_ATTACK, LOGOUT_ALL, SESSION_REVOKED,
	REGISTER, PASSWORD_CHANGED, PASSWORD_RESET, DELETE_USER, ROLE_CHANGED, STATUS_CHANGED, ACCESS_TOGGLED,
	INVALID_TOKEN, REVOKED_TOKEN_USAGE, EXPIRED_TOKEN_USAGE, ACCOUNT_UNLOCKED, VIEW_ACTIVE_SESSIONS, VIEW_USERS,
	VIEW_USER, SELF_ACTION_BLOCKED, REGISTRATION_OTP_SENT, VIEW_PROFILE, SESSION_INVALIDATED, TOKEN_REVOKED, SYSTEM_MAINTENANCE_ENABLED, SYSTEM_MAINTENANCE_DISABLED, SYSTEM_CACHE_CLEARED, PERMISSION_CACHE_REFRESHED, REGISTRATION_REJECTED, REGISTRATION_APPROVED, VIEW_PENDING_REGISTRATIONS

}
