spring.application.name=eureka-server


server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# =====================================================
# ACTUATOR
# =====================================================

management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name=Eureka Discovery Server
info.app.description=Netflix Eureka Service Registry
info.app.version=1.0.0