spring.application.name=eureka-server

server.port=8761

spring.cloud.config.uri=${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

# =====================================================
# EUREKA SERVER
# =====================================================

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.enable-self-preservation=true

eureka.server.eviction-interval-timer-in-ms=60000

# =====================================================
# ACTUATOR
# =====================================================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.info.env.enabled=false

# =====================================================
# APPLICATION INFO
# =====================================================

info.app.name=Eureka Discovery Server
info.app.description=Netflix Eureka Service Registry
info.app.version=1.0.0
info.app.owner=Harinitech
info.app.environment=local

# =====================================================
# LOGGING
# =====================================================

logging.level.root=INFO

logging.level.com.netflix.eureka=INFO

logging.level.org.springframework.cloud.netflix.eureka=INFO